# Generated by Django 5.0.6 on 2024-07-05 11:07

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=25, prefix='DEX', unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=25, prefix='217', unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='pin_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=25, prefix='', unique=True),
        ),
    ]
