# Generated by Django 5.0.6 on 2024-07-18 08:53

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_creditcard_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=15, max_length=20, prefix='CARD', unique=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=16, max_length=20, prefix='451', unique=True),
        ),
    ]
